var aNavData=[
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[],
	[]
]

var aCateContentData=[
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米2",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MIx",
		},
	]
]

// <li class="shouji clearfix">
	// 	<a href="#">
	// 		<img src="imgs/p1.jpg" alt="" class="road1">
	// 		<p class="p1">小米9&nbsp;6GB+128GB</p>
	// 		<p class="p2">骁龙855，索尼4800万超广角微距三摄</p>
	// 		<p class="p3">2999元</p>
	// 		<p class="biaoqian">新品</p>
	// 	</a>

	// 	<div class="yincang">
	// 		<p class="ppn">小小的 喜欢 希望可以用久一点 还是不错的</p>
	// 		<p class="ppj">来自2156774032用户的评价</p>
	// 	</div>
// </li>
var aElect=[
	[
		{
			url:"https//www.kuazhu.com",
			src:"imgs/p2.jpg",
			name:"小米9&nbsp;6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:2999,
			del:3999,
			flag:{
				class:"biaoqian",
				name:"新品"
			},
			view:{
				common:"小小的 喜欢 希望可以用久一点 还是不错的",
				author:"来自2156774032用户的评价"
			}
		},
		{
			url:"https//www.kuazhu.com",
			src:"imgs/p2.jpg",
			name:"小米9&nbsp;6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:2999,
			del:3999,
			flag:{
				class:"biaoqian",
				name:"新品"
			},
			view:{
				common:"小小的 喜欢 希望可以用久一点 还是不错的",
				author:"来自2156774032用户的评价"
			}
		},
		{
			url:"https//www.kuazhu.com",
			src:"imgs/p2.jpg",
			name:"小米9&nbsp;6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:2999,
			del:3999,
			flag:{
				class:"biaoqian",
				name:"新品"
			},
			view:{
				common:"小小的 喜欢 希望可以用久一点 还是不错的",
				author:"来自2156774032用户的评价"
			}
		},
		{
			url:"https//www.kuazhu.com",
			src:"imgs/p2.jpg",
			name:"小米9&nbsp;6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:2999,
			del:3999,
			flag:{
				class:"biaoqian",
				name:"新品"
			},
			view:{
				common:"小小的 喜欢 希望可以用久一点 还是不错的",
				author:"来自2156774032用户的评价"
			}
		},
		{
			url:"https//www.kuazhu.com",
			src:"imgs/p2.jpg",
			name:"小米9&nbsp;6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:2999,
			del:3999,
			flag:{
				class:"biaoqian",
				name:"新品"
			},
			view:{
				common:"小小的 喜欢 希望可以用久一点 还是不错的",
				author:"来自2156774032用户的评价"
			}
		},
		{
			url:"https//www.kuazhu.com",
			src:"imgs/p2.jpg",
			name:"小米9&nbsp;6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:2999,
			del:3999,
			flag:{
				class:"biaoqian",
				name:"新品"
			},
			view:{
				common:"小小的 喜欢 希望可以用久一点 还是不错的",
				author:"来自2156774032用户的评价"
			}
		},
		{
			url:"https//www.kuazhu.com",
			src:"imgs/p2.jpg",
			name:"小米9&nbsp;6GB+128GB",
			des:"骁龙855，索尼4800万超广角微距三摄",
			price:2999,
			del:3999,
			flag:{
				class:"biaoqian",
				name:"新品"
			},
			view:{
				ppn:"小小的 喜欢 希望可以用久一点 还是不错的",
				ppj:"来自2156774032用户的评价"
			}
		},
		{
			topname:"小米净水器....",
			topprice:"4399元",
			topimg:"imgs/p2.jpg",
			bottomname:"浏览更多",
			bottomthe:"热门",
			bottomicon:"&#xe615;"
		}
	],
	[],
	[],
	[]
]